// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC4rUivbn7Fm59azDTroxOmzZKZYboJ8c',
    appId: '1:485345113093:web:782b4a5302ab0e4b97986c',
    messagingSenderId: '485345113093',
    projectId: 'iitti-community-platform',
    authDomain: 'iitti-community-platform.firebaseapp.com',
    storageBucket: 'iitti-community-platform.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1TikmwQY4ev_D0jN9NqHZJrAox0Fyk4M',
    appId: '1:485345113093:android:ca8a8f7d40219ff997986c',
    messagingSenderId: '485345113093',
    projectId: 'iitti-community-platform',
    storageBucket: 'iitti-community-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWLU-nYbJ8uDH0zE4nnTkMG8trXtEm_Sw',
    appId: '1:485345113093:ios:8357f6232672de7f97986c',
    messagingSenderId: '485345113093',
    projectId: 'iitti-community-platform',
    storageBucket: 'iitti-community-platform.firebasestorage.app',
    iosBundleId: 'com.example.iittiCommunityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWLU-nYbJ8uDH0zE4nnTkMG8trXtEm_Sw',
    appId: '1:485345113093:ios:8357f6232672de7f97986c',
    messagingSenderId: '485345113093',
    projectId: 'iitti-community-platform',
    storageBucket: 'iitti-community-platform.firebasestorage.app',
    iosBundleId: 'com.example.iittiCommunityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC4rUivbn7Fm59azDTroxOmzZKZYboJ8c',
    appId: '1:485345113093:web:5306579d04d9a43297986c',
    messagingSenderId: '485345113093',
    projectId: 'iitti-community-platform',
    authDomain: 'iitti-community-platform.firebaseapp.com',
    storageBucket: 'iitti-community-platform.firebasestorage.app',
  );
}
